
const styles = theme => ({
  // Neighborhood Card Styles
  root: {
    backgroundColor: "#ffffff",
    backgroundImage:  props => `url(http://www.nomadville.xyz/api/nbdata/static/city-img/${props.image}.jpg)`,
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: "24px",
    margin: "0 4px",
    width: "257px",
    cursor: "pointer",
    marginBottom: "1em",
  },
  heartContainer: {
    zIndex: 10,
    "&:hover": {
      backgroundColor: "transparent",
    },
  },
  heartIcon: {
    height: "24px",
    width: "24px",
    margin: "16px 15px 0 0",
    cursor: "pointer"
  },
  title: {
    padding: "1em",
    textOverflow: "ellipsis",
    overflow: "hidden",
    color: "white",
    fontSize: 20,
    fontFamily: "Poppins",
    fontWeight: "600",
    textShadow: "0 2px 9px #303339",
    textAlign: "center",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  scoreValue: {
    color: "#FFF",
    fontSize: 12,
    fontFamily: "Poppins",
    fontWeight: "600",
  },
  scoreContainer: {
    width: "35px",
    height: "35px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#575ff9",
    opacity: 0.9,
    boxShadow: "0 3px 7px 0 rgba(148, 95, 233, 0.71)",
    margin: "12px",
  },
  scoreContainerFav: {
    width: "35px",
    height: "35px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ff0061",
    opacity: 0.9,
    boxShadow: "0 3px 7px 0 rgba(250, 2, 98, 0.7)",
    margin: "12px",
  },

  //BACK SIDE CSS
  backSideRoot: {
    backgroundColor: "#ffffff",
    width: "257px",
    cursor: "pointer",
    height: "179px",
    margin: "0 4px",
    borderRadius: "24px",
    marginBottom: "1em",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  backSideHeart: {
    width: "64",
    height: "60",
    margin: "10px 40.8px 4px 39.8px",
  },
  backSideTitle: {
    margin: "4px 27.8px 2px 27.3px",
    fontFamily: "Poppins",
    fontSize: 14.2,
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: 1.06,
    letterSpacing: "normal",
    textAlign: "center",
    color: "#323643",
  },
  backSideDesc: {
    margin: "2px 0 14px",
    fontFamily: "Poppins",
    fontSize: 12.7,
    fontWeight: 300,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: 1.18,
    letterSpacing: "normal",
    textAlign: "center",
    color: "#323643",
  },
  backSideDetail: {
    margin: "14px 0 9px",
    fontFamily: "Poppins",
    fontSize: 12.7,
    fontWeight: 600,
    fontStretch: "normal",
    fontStyle: "normal",
    lineHeight: 0.87,
    letterSpacing: "normal",
    textAlign: "center",
    color: "#323643",
    textDecoration: "underline",
  }
});

export default styles;
