module.exports.propArr= [
    {'shortName': 'filters_City_Area', 'longName': 'City Area'},
    {'shortName': 'filters_Town_Area', 'longName': 'Town Area'},
    {'shortName': 'filters_Village_Area', 'longName': 'Village Area'},
    {'shortName': 'filters_Low_hurricane_risk', 'longName': 'Low Hurricane Risk'},
    {'shortName': 'filters_Low_flooding', 'longName': 'Low Flooding'},
    {'shortName': 'filters_Low_humidity', 'longName': 'Low Humidity'},
    {'shortName': 'filters_Clean_air', 'longName': 'Clean Air'},
    {'shortName': 'filters_Fast_internet_speed', 'longName': 'Fast Internet Speed'},
    {'shortName': 'filters_Fast_commute', 'longName': 'Fast Commute'},
    {'shortName': 'filters_Clean', 'longName': 'Clean'},
    {'shortName': 'filters_Best_performing_universities', 'longName': 'Best Performing Universities'},
    {'shortName': 'filters_Carsharing', 'longName': 'Carsharing'},
    {'shortName': 'filters_Transit_bus', 'longName': 'Transit Bus'},
    {'shortName': 'filters_Intercity_rail', 'longName': 'Intercity Rail'},
    {'shortName': 'filters_Intercity_bus', 'longName': 'Intercity Bus'},
    {'shortName': 'filters_Low_property_tax', 'longName': 'Low Property Tax'},
    {'shortName': 'filters_Low_sales_tax', 'longName': 'Low Sales Tax'},
    {'shortName': 'filters_Low_public_service_tax', 'longName': 'Low Public Service Tax'},
    {'shortName': 'filters_High_paying_jobs', 'longName': 'High Paying Jobs'},
    {'shortName': 'filters_Low_unemployment', 'longName': 'Low Unemployment'},
    {'shortName': 'filters_Startups_presence', 'longName': 'filters_Startups_presence'},
    {'shortName': 'filters_Easy_to_do_business', 'longName': 'Easy To Do Business'},
    {'shortName': 'filters_Good_healthcare', 'longName': 'Good Healthcare'},
    {'shortName': 'filters_Quality_nursing_homes', 'longName': 'Quality Nursing Homes'},
    {'shortName': 'filters_Good_childcare', 'longName': 'Good Childcare'},
    {'shortName': 'filters_Great_hospitals', 'longName': 'Great Hospitals'},
    {'shortName': 'filters_High_household_income', 'longName': 'High Household Income'},
    {'shortName': 'filters_Low_gun_ownership', 'longName': 'Low Gun Ownership'},
    {'shortName': 'filters_High_gun_ownership', 'longName': 'High Gun Ownership'},
    {'shortName': 'filters_Low_crime_rate', 'longName': 'Low Crime Rate'},
    {'shortName': 'filters_Low_property_crime', 'longName': 'Low Property Crime'},
    {'shortName': 'filters_Walkable', 'longName': 'Walkable'},
    {'shortName': 'filters_Quality_tap_water', 'longName': 'Quality Tap Water'},
    {'shortName': 'filters_Low_noise', 'longName': 'Low Noise'},
    {'shortName': 'filters_Free_Wifi', 'longName': 'Free Wifi'},
    {'shortName': 'filters_Low_traffic', 'longName': 'Low Traffic'},
    {'shortName': 'filters_Low_homelesness', 'longName': 'Low Home lessness'},
    {'shortName': 'filters_Cycling_friendly', 'longName': 'Cycling Friendly'},
    {'shortName': 'filters_Very_conservative', 'longName': 'Very Conservative'},
    {'shortName': 'filters_Somewhat_conservative', 'longName': 'Somewhat Conservative'},
    {'shortName': 'filters_Middle_of_the_road', 'longName': 'Middle Of The Road'},
    {'shortName': 'filters_Somewhat_liberal', 'longName': 'Somewhat Liberal'},
    {'shortName': 'filters_Very_liberal', 'longName': 'Very Liberal'},
    {'shortName': 'filters_Young_population', 'longName': 'Young Population'},
    {'shortName': 'filters_Aging_population', 'longName': 'Aging Population'},
    {'shortName': 'filters_Ethnicaly_diverse', 'longName': 'Ethnicaly Diverse'},
    {'shortName': 'filters_English_speakers', 'longName': 'English Speakers'},
    {'shortName': 'filters_Spanish_speakers', 'longName': 'Spanish Speakers'},
    {'shortName': 'filters_French_speakers', 'longName': 'French Speakers'},
    {'shortName': 'filters_Chinese_speakers', 'longName': 'Chinese Speakers'},
    {'shortName': 'filters_LGBTQ_friendly', 'longName': 'LGBTQ Friendly'},
    {'shortName': 'filters_Foreign_born', 'longName': 'Foreign Born'},
    {'shortName': 'filters_New_residents', 'longName': 'New Residents'},
    {'shortName': 'filters_Best_performing_schools', 'longName': 'Best Performing Schools'},
    {'shortName': 'filters_Students_per_classroom_teacher', 'longName': 'Students Per Classroom Teacher'},
    {'shortName': 'filters_Below_market_house_price', 'longName': 'Below Market House Price'},
    {'shortName': 'filters_Below_market_rental_price', 'longName': 'Below Market Rental Price'},
    {'shortName': 'filters_High_home_ownership_rate', 'longName': 'High Home Ownership Rate'},
    {'shortName': 'filters_Low_vacancy_rate', 'longName': 'Low Vacancy Rate'},
    {'shortName': 'filters_Newer_housing', 'longName': 'Newer Housing'}
]