
const styles = theme => ({

  // Matcher Footer Styles
  matchButton: {
    border: "1px solid #979797",
    backgroundColor: "transparent",
    padding: "10px 40px",
    borderRadius: "22.5px",
    textTransform: "none",
    "&:hover": {
      backgroundColor: "transparent",
    },
  },
  nMatcher: {
    height: "104px",
    width: "70px",
    position: "absolute",
    bottom: "30px",
    left: "50%",
    transform: "translateX(-50%)",
  },
  restartMatcherButton: {
    color: "#323643",
    textTransform: "none",
    position: "relative",
    // padding: "8px 45px",
    "&:hover": {
      backgroundColor: "transparent",
    },
  },
  rMatcherButtonIcon: {
    marginRight: "5px",
    width: "14px",
    height: "12px",
  },
  bottomBox: {
    height: "74px",
    width: "100%",
    backgroundColor: "#fff",
    boxShadow: "0 6px 10px 0 rgba(14, 31, 53, 0.12), 0 12px 18px 0 rgba(14, 31, 53, 0.2), 0 20px 40px -1px rgba(14, 31, 53, 0.12)",
    position: "fixed",
    bottom: 0,
    right: 0,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 4,
  },
  thunder: {
    height: "32px",
    width: "32px",
    position: "absolute",
    bottom: "143%",
    left: "50%",
    transform: "translateX(-50%)",
  },
  logo: {
    marginLeft: "12px",
  },
  splitButton : {
    backgroundColor: "#323643",
    display: "inline-flex",
    padding: "4px",
    borderRadius: "24px",
    opacity: "77%",
    position: "absolute",
    left: "50%",
    transform: "translate(-50%)",
    marginTop: "12px",
    zIndex: 2,
  },
  splitButtonView: {
    backgroundColor: "#323643",
    display: "inline-flex",
    padding: "4px",
    borderRadius: "24px",
    opacity: "77%",
    /* position: absolute;
    left: 50%;
    transform: translate(-50%); */
    marginTop: "12px",
    left: "37px",
    position: "relative",
    zIndex: 2,
  },
  splitButtonItem: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    float: "left",
    backgroundColor: "transparent",
    borderRadius: "24px",
    padding: "4px 24px",
    cursor: "pointer",
    color: "#fff",
    opacity: "50%",
  },
  splitButtonItemActive: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f2f4f4",
    borderRadius: "24px",
    padding: "4px 24px",
    cursor: "pointer",
    color: "#323643",
  },
  dropDown: {
    backgroundColor: "#323643",
    height: "40px",
    width: "200px",
    display: "inline-flex",
    position: "absolute",
    marginTop: "12px",
    right: "37px",
    cursor: "pointer",
    zIndex: 2,
  },
  dropDownContent: {
    height: "calc(100vh - 15%)",
    width: "362px",
    backgroundColor: "#fff",
    position: "absolute",
    right: "37px",
    marginTop: "9px",
    paddingTop: "24px",
    overflow: "hidden",
    opacity: "90%",
    zIndex: 3,
  },
  dropDownItem: {
    display: "flex",
    marginLeft: "16%",
    alignItems: "center",
    color: "#000",
  },
  percentMatch: {
    display: "flex",
    marginLeft: "12%",
    alignItems: "center",
    color: "#fff",
  },
  navigation: {
    color: "#323643",
    textDecoration: "none",
    cursor: "pointer",
    padding: "8px 45px",
    /* padding-left : 20px; */
  },
  SwipeView: {
    backgroundColor: "#323643",
    opacity: 0.77,
  },
  leftGroupButtons: {
    backgroundColor: "thistle",
  },
  bottomNavigationButtons: {
    display: "inline-flex",
  },
  restartMatcher: {
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    left: "30%",
    bottom: "20%",
    cursor: "pointer",
  },
  homeMatcher: {
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    right: "30%",
    bottom: "20%",
  },
  homeMatcherActive: {
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    right: "30%",
    bottom: "20%",
    cursor: "pointer",
  },
  homeMatcherThunderActive: {
    height: "76px",
    width: "74px",
    position: "absolute",
    left: "50%",
    transform: "translate(-50%)",
    bottom: "30px",
    zIndex: 2,
    transition: "ease 0.5s",
  },
  homeMatcherThunder: {
    height: "62px",
    width: "60px",
    position: "absolute",
    left: "50%",
    transform: "translate(-50%)",
    bottom: "30px",
    zIndex: 2,
    transition: "ease 0.25s",
  }
  
});

export default styles;
